### ISSUE TITLE
BungeeCord

### ISSUE THREAD

**Issue by ScottM911** [GrimReaper52498/Punish#2]
Does the plugin support bungeecord?

**Comment by GrimReaper52498** [comment]
As of right no. However Im working on a MySQL version which will work for BungeeCord. But you can always use the plugin to run commands for other plugins that do support BungeeCord for the time being (:

**Comment by GrimReaper52498** [comment]
Right now, no*

**Comment by ScottM911** [comment]
Okay, thanks for the info!
